TABLE_LOG = 'log'

BOOKS = dict()
BOOKS.update({'10bet': '10bet'})
BOOKS.update({'188BET': '188bet'})
BOOKS.update({'18Bet': '18bet'})
BOOKS.update({'198Bet': '198bet'})
BOOKS.update({'1Bet': '1bet'})
BOOKS.update({'1xBet': '1xbet'})
BOOKS.update({'1xBit': '1xbit'})
BOOKS.update({'20Bet': '20bet'})
BOOKS.update({'22Bet': '22bet'})
BOOKS.update({'31Bet': '31bet'})
BOOKS.update({'32Red': '32red'})
BOOKS.update({'3et': '3et'})
BOOKS.update({'7Bet LT': '7bet.lt'})
BOOKS.update({'Admiral AT': 'admiral'})
BOOKS.update({'AdmiralBet RO': 'admiralbet.ro'})
BOOKS.update({'All British Casino': 'allbritishcasino'})
BOOKS.update({'AlphaWin': 'alphawin'})
BOOKS.update({'Apuesta Total': 'apuestatotal'})
BOOKS.update({'ATG SE': 'atg.se'})
BOOKS.update({'Bally Bet': 'ballybet'})
BOOKS.update({'BC.Game': 'bcgame'})
BOOKS.update({'Bet3000': 'bet3000'})
BOOKS.update({'bet365': 'bet365'})
BOOKS.update({'bet365': 'bet365-test'})
BOOKS.update({'bet365 DE': 'bet365.de'})
BOOKS.update({'Bet9ja': 'bet9ja'})
BOOKS.update({'Betano': 'betano'})
BOOKS.update({'Bet-At-Home': 'betathome'})
BOOKS.update({'Betcenter BE': 'betcenter.be'})
BOOKS.update({'Betcity NL': 'betcity'})
BOOKS.update({'BetClic FR': 'betclic.fr'})
BOOKS.update({'BetClic PL': 'betclic.pl'})
BOOKS.update({'BetClic PT': 'betclic.pt'})
BOOKS.update({'BetFair Exchange': 'betfair-ex'})
BOOKS.update({'BetFair Sportsbook': 'betfair-spb'})
BOOKS.update({'Betfred': 'betfred'})
BOOKS.update({'Betfury': 'betfury'})
BOOKS.update({'BetiBet': 'betibet'})
BOOKS.update({'Betika KE': 'betika'})
BOOKS.update({'BetISN': 'betisn'})
BOOKS.update({'BetMGM': 'betmgm'})
BOOKS.update({'Betnacional': 'betnacional'})
BOOKS.update({'BetOnRed': 'betonred'})
BOOKS.update({'BetParx': 'betparx'})
BOOKS.update({'BetPlay': 'betplay'})
BOOKS.update({'BetRivers': 'betrivers'})
BOOKS.update({'Betsafe': 'betsafe'})
BOOKS.update({'Betsafe LT': 'betsafe.lt'})
BOOKS.update({'Betsson': 'betsson'})
BOOKS.update({'BetUK': 'betuk'})
BOOKS.update({'BetVictor': 'betvictor'})
BOOKS.update({'Betway': 'betway'})
BOOKS.update({'BetWinner': 'betwinner'})
BOOKS.update({'BFB247': 'bfb247'})
BOOKS.update({'Bingoal BE': 'bingoal.be'})
BOOKS.update({'Bluechip': 'bluechip'})
BOOKS.update({'Bolsa de Aposta Sportsbook': 'bolsadeaposta-spb'})
BOOKS.update({'BookMaker EU': 'bookmaker.eu'})
BOOKS.update({'Borgata Online Sports': 'borgata'})
BOOKS.update({'BoyleSports': 'boylesports'})
BOOKS.update({'Bpremium': 'bpremium'})
BOOKS.update({'Bwin': 'bwin'})
BOOKS.update({'Bwin ES': 'bwin.es'})
BOOKS.update({'Bwin FR': 'bwin.fr'})
BOOKS.update({'Bwin IT': 'bwin.it'})
BOOKS.update({'Caliente MX': 'caliente'})
BOOKS.update({'CampeonBet': 'campeonbet'})
BOOKS.update({'CASHPOINT': 'cashpoint'})
BOOKS.update({'Cloudbet': 'cloudbet'})
BOOKS.update({'Coolbet': 'coolbet'})
BOOKS.update({'Coral': 'coral'})
BOOKS.update({'CrazyBuzzer': 'crazybuzzer'})
BOOKS.update({'Cricbaba': 'cricbaba'})
BOOKS.update({'DACHBET': 'dachbet'})
BOOKS.update({'Dafabet': 'dafabet'})
BOOKS.update({'Draftkings': 'draftkings'})
BOOKS.update({'Dream.bet': 'dreambet'})
BOOKS.update({'Duelbits': 'duelbits'})
BOOKS.update({'ESPN Bet': 'espnbet'})
BOOKS.update({'Esportiva Bet': 'esportivabet'})
BOOKS.update({'Estrela Bet': 'estrelabet'})
BOOKS.update({'FanDuel': 'fanduel'})
BOOKS.update({'FDJ': 'fdj'})
BOOKS.update({'FEZbet': 'fezbet'})
BOOKS.update({'Fortebet UG': 'fortebet.ug'})
BOOKS.update({'FreshBet': 'freshbet'})
BOOKS.update({'Fun88 UK': 'fun88.co.uk'})
BOOKS.update({'Gamebookers': 'gamebookers'})
BOOKS.update({'Genybet FR': 'genybet.fr'})
BOOKS.update({'Goldenbet': 'goldenbet'})
BOOKS.update({'GreatWin': 'greatwin'})
BOOKS.update({'Grosvenor': 'grosvenor'})
BOOKS.update({'Hollywoodbets': 'hollywoodbets'})
BOOKS.update({'INDIBET': 'indibet'})
BOOKS.update({'Inkabet': 'inkabet'})
BOOKS.update({'Interwetten': 'interwetten'})
BOOKS.update({'IviBet': 'ivibet'})
BOOKS.update({'JackBit': 'jackbit'})
BOOKS.update({'Jacks': 'jacks'})
BOOKS.update({'Kaiyun Sports': 'kaiyun'})
BOOKS.update({'KTO': 'kto'})
BOOKS.update({'Ladbrokes': 'ladbrokes'})
BOOKS.update({'Ladbrokes DE': 'ladbrokes.de'})
BOOKS.update({'LeoVegas': 'leovegas'})
BOOKS.update({'LibraBet': 'librabet'})
BOOKS.update({'LiliBet': 'lilibet'})
BOOKS.update({'LiveScoreBet': 'livescorebet'})
BOOKS.update({'Lottoland': 'lottoland'})
BOOKS.update({'MARCAapuestas': 'marcaapuestas'})
BOOKS.update({'MegaPari': 'megapari'})
BOOKS.update({'MelBet': 'melbet'})
BOOKS.update({'Merkur Bets': 'merkurbets'})
BOOKS.update({'Mozzart Bet': 'mozzartbet'})
BOOKS.update({'MrBit RO': 'mrbit.ro'})
BOOKS.update({'MrGreen': 'mrgreen'})
BOOKS.update({'Mr. Jack': 'mrjack.bet'})
BOOKS.update({'MyStake': 'mystake'})
BOOKS.update({'N1Bet': 'n1bet'})
BOOKS.update({'Napoleon Sports BE': 'napoleonsports.be'})
BOOKS.update({'NetBet': 'netbet'})
BOOKS.update({'NetBet FR': 'netbet.fr'})
BOOKS.update({'Nextbet': 'nextbet'})
BOOKS.update({'Ninecasino': 'ninecasino'})
BOOKS.update({'NordicBet': 'nordicbet'})
BOOKS.update({'OddSet': 'oddset'})
BOOKS.update({'OdiBets': 'odibets'})
BOOKS.update({'Paddy Power': 'paddypower'})
BOOKS.update({'PAF': 'paf'})
BOOKS.update({'PAGBET': 'pagbet'})
BOOKS.update({'PariMatch UK': 'parimatch.co.uk'})
BOOKS.update({'PremiumBet77': 'pb77'})
BOOKS.update({'Pinnacle Sports': 'pinnacle'})
BOOKS.update({'Piwi247': 'piwi247'})
BOOKS.update({'Pix Bet': 'pixbet'})
BOOKS.update({'PMU': 'pmu'})
BOOKS.update({'PointsBet': 'pointsbet'})
BOOKS.update({'PokerStars': 'pokerstars'})
BOOKS.update({'PokerStars ES': 'pokerstars.es'})
BOOKS.update({'PokerStars FR': 'pokerstars.fr'})
BOOKS.update({'PokerStars IT': 'pokerstars.it'})
BOOKS.update({'PokerStars RO': 'pokerstars.ro'})
BOOKS.update({'PokerStars UK': 'pokerstars.uk'})
BOOKS.update({'Powbet': 'powbet'})
BOOKS.update({'PS3838': 'ps3838'})
BOOKS.update({'Qbet': 'qbet'})
BOOKS.update({'QuickWin': 'quickwin'})
BOOKS.update({'Rabona': 'rabona'})
BOOKS.update({'RajBet': 'rajbets'})
BOOKS.update({'RocketPlay': 'rocketplay'})
BOOKS.update({'Rollbit': 'rollbit'})
BOOKS.update({'Rolletto': 'rolletto'})
BOOKS.update({'Roobet': 'roobet'})
BOOKS.update({'Rushbet CO': 'rushbet.co'})
BOOKS.update({'SBOBET': 'sbobet'})
BOOKS.update({'SharpBet': 'sharpbet'})
BOOKS.update({'SingBet': 'singbet'})
BOOKS.update({'Sisal IT': 'sisal'})
BOOKS.update({'SkyBet': 'skybet'})
BOOKS.update({'888Sport': 'sport888'})
BOOKS.update({'888Sport IT': 'sport888.it'})
BOOKS.update({'Sportaza': 'sportaza'})
BOOKS.update({'SportingBet': 'sportingbet'})
BOOKS.update({'Sporting Index': 'sportingindex'})
BOOKS.update({'Sporttip': 'sporttip'})
BOOKS.update({'sportwetten.de': 'sportwetten.de'})
BOOKS.update({'SportyBet': 'sportybet'})
BOOKS.update({'Spreadex': 'spreadex'})
BOOKS.update({'Stake.com': 'stake'})
BOOKS.update({'Starcasino BE': 'starcasino'})
BOOKS.update({'Stoiximan': 'stoiximan'})
BOOKS.update({'STS PL': 'sts.pl'})
BOOKS.update({'SugarHouse': 'sugarhouse'})
BOOKS.update({'Sultanbet': 'sultanbet'})
BOOKS.update({'Superbet': 'superbet'})
BOOKS.update({'Svenska Spel': 'svenskaspel'})
BOOKS.update({'Tab AU': 'tab.com.au'})
BOOKS.update({'TABtouch': 'tabtouch'})
BOOKS.update({'theScore': 'thescore'})
BOOKS.update({'Tipico DE': 'tipico'})
BOOKS.update({'TippmixPRO': 'tippmixpro'})
BOOKS.update({'TipTorro': 'tiptorro'})
BOOKS.update({'tipwin': 'tipwin'})
BOOKS.update({'Unibet': 'unibet'})
BOOKS.update({'Unibet BE': 'unibet.be'})
BOOKS.update({'Unibet UK': 'unibet.co.uk'})
BOOKS.update({'Unibet AU': 'unibet.com.au'})
BOOKS.update({'Unibet DK': 'unibet.dk'})
BOOKS.update({'Unibet ES': 'unibet.es'})
BOOKS.update({'Unibet FR': 'unibet.fr'})
BOOKS.update({'Unibet IT': 'unibet.it'})
BOOKS.update({'Unibet NL': 'unibet.nl'})
BOOKS.update({'Unibet RO': 'unibet.ro'})
BOOKS.update({'Unibet SE': 'unibet.se'})
BOOKS.update({'Vave': 'vave'})
BOOKS.update({'Vbet': 'vbet'})
BOOKS.update({'Vertex': 'vertex'})
BOOKS.update({'Virginbet': 'virginbet'})
BOOKS.update({'Vistabet': 'vistabet'})
BOOKS.update({'Wazamba': 'wazamba'})
BOOKS.update({'WELTBET': 'weltbet'})
BOOKS.update({'Wettarena': 'wettarena'})
BOOKS.update({'WilliamHill': 'williamhill'})
BOOKS.update({'Winamax DE': 'winamax.de'})
BOOKS.update({'Winamax ES': 'winamax.es'})
BOOKS.update({'Winamax FR': 'winamax.fr'})
BOOKS.update({'WinBet BG': 'winbet'})
BOOKS.update({'WinBet RO': 'winbet.ro'})
BOOKS.update({'Winpot MX': 'winpot.mx'})
BOOKS.update({'Winz.io': 'winz.io'})
BOOKS.update({'WOLFBET': 'wolfbet'})
BOOKS.update({'WPlay CO': 'wplay.co'})
BOOKS.update({'YesPlay': 'yesplay'})
BOOKS.update({'ZEbet FR': 'zebet.fr'})