import streamlit as st

TABLE_USERS = 'users'

BOOKS = set()
BOOKS.add('10Bet')
BOOKS.add('10Bet (SE)')
BOOKS.add('10Bet (ZA)')
BOOKS.add('10Bet (UK)')
BOOKS.add('10Bet (MX)')
BOOKS.add('888Casino (Arabic)')
BOOKS.add('888Games')
BOOKS.add('10Cric')
BOOKS.add('188Bet')
BOOKS.add('188Bet (PT)')
BOOKS.add('188Bet (Sbk)')
BOOKS.add('188Bet (ZH)')
BOOKS.add('HGA030 (Crown)')
BOOKS.add('HGA035 (Crown)')
BOOKS.add('18Bet')
BOOKS.add('BabiBet')
BOOKS.add('Hollywoodbets (UK)')
BOOKS.add('MrSloty')
BOOKS.add('Premium Tradings')
BOOKS.add('RoyalistPlay')
BOOKS.add('1Bet (CO)')
BOOKS.add('Bet-Bra SB (BR)')
BOOKS.add('BetOBet')
BOOKS.add('BetOBet (CC)')
BOOKS.add('Bolsadeaposta SB (BR)')
BOOKS.add('1Win (Original)')
BOOKS.add('1xBet')
BOOKS.add('1xBet (AG)')
BOOKS.add('1xBet (BO)')
BOOKS.add('1xBet (ES)')
BOOKS.add('1xBet (MD)')
BOOKS.add('1xBet (NG)')
BOOKS.add('1xstavka (RU)')
BOOKS.add('Betandyou')
BOOKS.add('Linebet')
BOOKS.add('MegaPari')
BOOKS.add('Oppa88')
BOOKS.add('Pari-pesa')
BOOKS.add('Paripesa')
BOOKS.add('Paripesa (Asia)')
BOOKS.add('Paripesa (Biz)')
BOOKS.add('Paripesa (Com)')
BOOKS.add('Paripesa (Cool)')
BOOKS.add('Paripesa (ME)')
BOOKS.add('Paripesa (Net)')
BOOKS.add('Paripesa (NG)')
BOOKS.add('Paripesa (PT)')
BOOKS.add('Paripesa (Site)')
BOOKS.add('Paripesaut')
BOOKS.add('SapphireBet')
BOOKS.add('1xBet (IT)')
BOOKS.add('22Bet')
BOOKS.add('22Bet (NG)')
BOOKS.add('22win88')
BOOKS.add('Bestwinzz')
BOOKS.add('3et')
BOOKS.add('888sport')
BOOKS.add('888sport (DE)')
BOOKS.add('888sport (DK)')
BOOKS.add('888sport (ES)')
BOOKS.add('888sport (RO)')
BOOKS.add('MrGreen')
BOOKS.add('MrGreen (DK)')
BOOKS.add('MrGreen (SE)')
BOOKS.add('888sport (IT)')
BOOKS.add('AccessBet')
BOOKS.add('AdjaraBet')
BOOKS.add('Admiral (AT)')
BOOKS.add('Admiral (DE)')
BOOKS.add('AdmiralBet (ES)')
BOOKS.add('AdmiralCasino (UK)')
BOOKS.add('Swisslos (CH)')
BOOKS.add('AdmiralBet (IT)')
BOOKS.add('Afribet (NG)')
BOOKS.add('Betfred (ZA)')
BOOKS.add('AI Sports')
BOOKS.add('Akbets')
BOOKS.add('Apostaganha (BR)')
BOOKS.add('AsianOdds')
BOOKS.add('B1Bet (BR)')
BOOKS.add('Bahigo')
BOOKS.add('Kakeyo')
BOOKS.add('BaltBet (RU)')
BOOKS.add('BandBet (BR)')
BOOKS.add('BangBet')
BOOKS.add('Betsure')
BOOKS.add('BantuBet (AO)')
BOOKS.add('Bet2U2')
BOOKS.add('BetBaba (NG)')
BOOKS.add('Bet-at-home')
BOOKS.add('Bet-at-home (DE)')
BOOKS.add('Bet-Bra (BR)')
BOOKS.add('Bet365 (Fast)')
BOOKS.add('28365365')
BOOKS.add('365-808')
BOOKS.add('365sb')
BOOKS.add('365sport365')
BOOKS.add('878365')
BOOKS.add('Allsport365')
BOOKS.add('Bet365 (AU)')
BOOKS.add('Bet365 (BR)')
BOOKS.add('Bet365 (DE)')
BOOKS.add('Bet365 (ES)')
BOOKS.add('Bet365 (GR)')
BOOKS.add('Bet365 (IT)')
BOOKS.add('Bet365 (NL)')
BOOKS.add('Game-365 (CN)')
BOOKS.add('Bet365 (Full)')
BOOKS.add('Bet7')
BOOKS.add('Bet7k (BR)')
BOOKS.add('B2XBET (BR)')
BOOKS.add('BetBet (BR)')
BOOKS.add('BetGorillas (BR)')
BOOKS.add('Cassino (BR)')
BOOKS.add('Donald (BR)')
BOOKS.add('Vera (BR)')
BOOKS.add('Bet9ja')
BOOKS.add('Betadonis')
BOOKS.add('Betaland (IT)')
BOOKS.add('Betano')
BOOKS.add('Betano (CZ)')
BOOKS.add('Betano (DE)')
BOOKS.add('Betano (MX)')
BOOKS.add('Betano (RO)')
BOOKS.add('Betano (BR)')
BOOKS.add('Betano (PT)')
BOOKS.add('Betano (NG)')
BOOKS.add('Betao (BR)')
BOOKS.add('BravoBet (BR)')
BOOKS.add('Maxima (BR)')
BOOKS.add('R7Bet (BR)')
BOOKS.add('XpBet (BR)')
BOOKS.add('BetBoom (BR)')
BOOKS.add('BetBoom')
BOOKS.add('BetBoom (RU)')
BOOKS.add('Betboro')
BOOKS.add('Betboro (GH)')
BOOKS.add('Betcity')
BOOKS.add('Betcity (BY)')
BOOKS.add('Betcity (Net)')
BOOKS.add('Betcity (RU)')
BOOKS.add('Formula55 (TJ)')
BOOKS.add('Betcity (NL)')
BOOKS.add('SpeedyBet')
BOOKS.add('BetClic')
BOOKS.add('BetClic (FR)')
BOOKS.add('BetClic (IT)')
BOOKS.add('BetClic (PL)')
BOOKS.add('BetClic (PT)')
BOOKS.add('Betcris')
BOOKS.add('Betcris (DO)')
BOOKS.add('Betcris (MX)')
BOOKS.add('Betcris (PL)')
BOOKS.add('BetDaq2%')
BOOKS.add('BetDaSorte (BR)')
BOOKS.add('Afun (BR)')
BOOKS.add('BetDSI (EU)')
BOOKS.add('BetEsporte (BR)')
BOOKS.add('LanceDeSorte (BR)')
BOOKS.add('Betfair3% ① ≥ 1.01')
BOOKS.add('Betfair (AU)3% ① ≥ 1.01')
BOOKS.add('Betfair (BR)3% ① ≥ 1.01')
BOOKS.add('Betfair (RO)3% ① ≥ 1.01')
BOOKS.add('Betfair (SE)3% ① ≥ 1.01')
BOOKS.add('SatSport3% ① ≥ 1.01')
BOOKS.add('Sharpxch3% ① ≥ 1.01')
BOOKS.add('Tradexbr3% ① ≥ 1.01')
BOOKS.add('Betfair (ES)')
BOOKS.add('Betfair (IT)')
BOOKS.add('Betfair (MBR)')
BOOKS.add('Betfair SB')
BOOKS.add('Betfair SB (ES)')
BOOKS.add('Betfair SB (RO)')
BOOKS.add('Betfarm')
BOOKS.add('Betfirst (BE)')
BOOKS.add('Betflip')
BOOKS.add('Casobet (Sport)')
BOOKS.add('Fairspin')
BOOKS.add('Tether')
BOOKS.add('Weiss')
BOOKS.add('Betfred')
BOOKS.add('BetiBet')
BOOKS.add('Betika (KE)')
BOOKS.add('BetInAsia (Black)')
BOOKS.add('Bets (BR)')
BOOKS.add('Betinia')
BOOKS.add('Lottoland (UK)')
BOOKS.add('BetKing')
BOOKS.add('Betlive')
BOOKS.add('Betmaster')
BOOKS.add('Betnacional (BR)')
BOOKS.add('Betnation (NL)')
BOOKS.add('BetOnline (AG)')
BOOKS.add('BetOnline (AG)')
BOOKS.add('SportsBetting (AG)')
BOOKS.add('TigerGaming')
BOOKS.add('BetPawa (NG)')
BOOKS.add('BetPawa (CM)')
BOOKS.add('BetPawa (GH)')
BOOKS.add('BetPawa (KE)')
BOOKS.add('BetPawa (RW)')
BOOKS.add('BetPawa (TZ)')
BOOKS.add('BetPawa (UG)')
BOOKS.add('BetPawa (ZM)')
BOOKS.add('BetPix365 (BR)')
BOOKS.add('Vaidebet')
BOOKS.add('BetRebels')
BOOKS.add('21Bets')
BOOKS.add('7bet (LT)')
BOOKS.add('Bankonbet')
BOOKS.add('BaumBet (RO)')
BOOKS.add('bBets')
BOOKS.add('Betinia (DK)')
BOOKS.add('Betinia (SE)')
BOOKS.add('Betmotion')
BOOKS.add('BetNFlix')
BOOKS.add('Betvision')
BOOKS.add('CampoBet')
BOOKS.add('CampoBet (DK)')
BOOKS.add('DoradoBet')
BOOKS.add('Ecuabet')
BOOKS.add('ElaBet (GR)')
BOOKS.add('Fastbet (IT)')
BOOKS.add('FezBet')
BOOKS.add('FrankSports (RO)')
BOOKS.add('Golden Palace (BE)')
BOOKS.add('Jokerbet (ES)')
BOOKS.add('LibraBet')
BOOKS.add('MrBit (BG)')
BOOKS.add('MrBit (RO)')
BOOKS.add('PowBet')
BOOKS.add('Rabona')
BOOKS.add('RtBet')
BOOKS.add('Sevenplay')
BOOKS.add('Spinanga')
BOOKS.add('Sportaza')
BOOKS.add('StarCasinoSport (BE)')
BOOKS.add('Betrivers (CA)')
BOOKS.add('Betrivers (AZ)')
BOOKS.add('Betsafe')
BOOKS.add('Bethard')
BOOKS.add('Betsafe (EE)')
BOOKS.add('Betsafe (LV)')
BOOKS.add('Betsafe (SE)')
BOOKS.add('Betsson')
BOOKS.add('Bets10')
BOOKS.add('Betsson (BR)')
BOOKS.add('Betsson (CO)')
BOOKS.add('Betsson (SE)')
BOOKS.add('Inkabet (PE)')
BOOKS.add('Betsson (ES)')
BOOKS.add('Betpark (BR)')
BOOKS.add('SupremaBet (BR)')
BOOKS.add('Betsson (FR)')
BOOKS.add('Betsson (GE)')
BOOKS.add('Betsson (GR)')
BOOKS.add('Betsmith')
BOOKS.add('Betsson (IT)')
BOOKS.add('Betsul (BR)')
BOOKS.add('Betters (PL)')
BOOKS.add('Lebull (PL)')
BOOKS.add('Betuk (UK)')
BOOKS.add('Betus (PA)')
BOOKS.add('BetVictor')
BOOKS.add('Parimatch (UK)')
BOOKS.add('Puntit (IN)')
BOOKS.add('BetWarrior')
BOOKS.add('BetWarrior (BR)')
BOOKS.add('BetWarrior (Caba)')
BOOKS.add('BetWarrior (MZA)')
BOOKS.add('BetWarrior (PBA)')
BOOKS.add('BetWarrior Apuestas (AR)')
BOOKS.add('LeoVegas (IT)')
BOOKS.add('MyBet')
BOOKS.add('Svenska Spel (SE)')
BOOKS.add('BetWay')
BOOKS.add('BetWay (DE)')
BOOKS.add('BetWay (MX)')
BOOKS.add('BetWay (IT)')
BOOKS.add('Betwgb')
BOOKS.add('AdmiralBet (RS)')
BOOKS.add('AdmiralBet (UG)')
BOOKS.add('Betxchange')
BOOKS.add('Bingoal (BE)')
BOOKS.add('BallyBet')
BOOKS.add('BetPlay (CO)')
BOOKS.add('Bingoal (NL)')
BOOKS.add('Desert Diamond')
BOOKS.add('Expekt (DK)')
BOOKS.add('Expekt (SE)')
BOOKS.add('Blaze')
BOOKS.add('4RaBet')
BOOKS.add('4RaBet (Play)')
BOOKS.add('Africa365')
BOOKS.add('BC.Game')
BOOKS.add('BetFury')
BOOKS.add('Betonred')
BOOKS.add('Betonred (NG)')
BOOKS.add('BetPlay')
BOOKS.add('BetTilt')
BOOKS.add('Betvip')
BOOKS.add('BilBet')
BOOKS.add('Bitz')
BOOKS.add('Blaze (BR)')
BOOKS.add('BloodMoon (CO)')
BOOKS.add('BlueChip')
BOOKS.add('Bons')
BOOKS.add('CasinoX')
BOOKS.add('Casinozer')
BOOKS.add('Casinozer (EU)')
BOOKS.add('FlaBet (BR)')
BOOKS.add('Fortunejack')
BOOKS.add('JetBet (BR)')
BOOKS.add('JonBet (BR)')
BOOKS.add('Joycasino')
BOOKS.add('KingpandaBet (BR)')
BOOKS.add('Lucky Block')
BOOKS.add('Lucky Block (Top)')
BOOKS.add('Opabet')
BOOKS.add('PinBet')
BOOKS.add('Pokerdom')
BOOKS.add('PuskasBet (BR)')
BOOKS.add('RajaBets')
BOOKS.add('Riobet')
BOOKS.add('Rivalry')
BOOKS.add('Rollbit')
BOOKS.add('RooBet')
BOOKS.add('Slots Safari (CO)')
BOOKS.add('Solcasino')
BOOKS.add('TrBET')
BOOKS.add('Yonibet')
BOOKS.add('Yonibet (EU)')
BOOKS.add('BoaBet')
BOOKS.add('Bodog (EU)')
BOOKS.add('Bovada (LV)')
BOOKS.add('BolsaDeAposta (BR)')
BOOKS.add('BolsaDeAposta TB (BR)')
BOOKS.add('BookMaker (EU)')
BOOKS.add('JustBet (CO)')
BOOKS.add('BoyleSports')
BOOKS.add('Brazino 777')
BOOKS.add('Brazino 777 (BY)')
BOOKS.add('Brazino 777 (IO)')
BOOKS.add('Wazobet')
BOOKS.add('BrBet (BR)')
BOOKS.add('BresBet')
BOOKS.add('Bumbet')
BOOKS.add('Bwin')
BOOKS.add('Betboo (BR)')
BOOKS.add('Betmgm (CA)')
BOOKS.add('Betmgm (MA)')
BOOKS.add('Betmgm (NY)')
BOOKS.add('Bwin (BE)')
BOOKS.add('Bwin (DE)')
BOOKS.add('Bwin (DK)')
BOOKS.add('Bwin (ES)')
BOOKS.add('Bwin (GR)')
BOOKS.add('Bwin (IT)')
BOOKS.add('Gamebookers')
BOOKS.add('Giocodigitale (IT)')
BOOKS.add('Ladbrokes (DE)')
BOOKS.add('Oddset (DE)')
BOOKS.add('Partypoker')
BOOKS.add('Sportingbet')
BOOKS.add('Sportingbet (BR)')
BOOKS.add('Sportingbet (DE)')
BOOKS.add('Sportingbet (GR)')
BOOKS.add('Sportingbet (ZA)')
BOOKS.add('Vistabet (GR)')
BOOKS.add('Bwin (FR)')
BOOKS.add('Bwin (PT)')
BOOKS.add('Caliente (MX)')
BOOKS.add('Betcha (PA)')
BOOKS.add('Marca Apuestas (ES)')
BOOKS.add('Wplay (CO)')
BOOKS.add('CampeonBet')
BOOKS.add('12Bet (UK)')
BOOKS.add('All British Casino')
BOOKS.add('ApuestaTotal')
BOOKS.add('Betaki (BR)')
BOOKS.add('Betanoshops (NG)')
BOOKS.add('Bettarget (UK)')
BOOKS.add('Betvision')
BOOKS.add('Br4bet')
BOOKS.add('GastonRed')
BOOKS.add('Greatwin')
BOOKS.add('Jogodeouro (BR)')
BOOKS.add('Karamba (UK)')
BOOKS.add('Lottland (IE)')
BOOKS.add('Lottoland')
BOOKS.add('MultiBet (BR)')
BOOKS.add('Playdoit (MX)')
BOOKS.add('StarCasino (NL)')
BOOKS.add('Vegas (HU)')
BOOKS.add('Winpot (MX)')
BOOKS.add('Casa Pariurilor (RO)')
BOOKS.add('Fortuna (RO)')
BOOKS.add('CasaDeApostas (BR)')
BOOKS.add('Betmais')
BOOKS.add('Cashpoint')
BOOKS.add('Betcenter (BE)')
BOOKS.add('Cashpoint (DK)')
BOOKS.add('MerkurBets (DE)')
BOOKS.add('CasinoPortugal (PT)')
BOOKS.add('CBet')
BOOKS.add('CBet (LT)')
BOOKS.add('Circus (BE)')
BOOKS.add('Circus (NL)')
BOOKS.add('CloudBet')
BOOKS.add('Codere (ES)')
BOOKS.add('Codere (AR)')
BOOKS.add('Codere (MX)')
BOOKS.add('Comeon')
BOOKS.add('Casinostugan')
BOOKS.add('Comeon (PL)')
BOOKS.add('Hajper')
BOOKS.add('Lyllo Casino')
BOOKS.add('MobileBet')
BOOKS.add('Nopeampi')
BOOKS.add('Pzbuk (PL)')
BOOKS.add('Saga Kingdom')
BOOKS.add('Snabbare')
BOOKS.add('SunMaker (DE)')
BOOKS.add('Comeon (NL)')
BOOKS.add('CoolBet')
BOOKS.add('CoolBet (CL)')
BOOKS.add('CoolBet (PE)')
BOOKS.add('Coral (UK)')
BOOKS.add('Crocobet')
BOOKS.add('CrystalBet (GE)')
BOOKS.add('DafaBet (ES)')
BOOKS.add('DafaBet (Sports)')
BOOKS.add('Amperjai')
BOOKS.add('Nextbet')
BOOKS.add('DafaBet OW (Saba)')
BOOKS.add('12Bet (Saba)')
BOOKS.add('12Bet (Saba-ID)')
BOOKS.add('12Bet (Saba-MY)')
BOOKS.add('CMD368 (Saba)')
BOOKS.add('M88 (Saba)')
BOOKS.add('W88Live (Saba)')
BOOKS.add('Danskespil (DK)')
BOOKS.add('DaznBet (ES)')
BOOKS.add('DaznBet (UK)')
BOOKS.add('DomusBet (IT)')
BOOKS.add('DoxxBet (SK)')
BOOKS.add('Draftkings')
BOOKS.add('Draftking (CT)')
BOOKS.add('DragonBet (UK)')
BOOKS.add('DripCasino')
BOOKS.add('Duelbits')
BOOKS.add('Easybet (ZA)')
BOOKS.add('Ebingo (ES)')
BOOKS.add('BetaBet')
BOOKS.add('BetaBet (Net)')
BOOKS.add('Betcoin (AG)')
BOOKS.add('ShansBet')
BOOKS.add('EDSBet')
BOOKS.add('Efbet (ES)')
BOOKS.add('Efbet (BG)')
BOOKS.add('Efbet (IT)')
BOOKS.add('Efbet (RO)')
BOOKS.add('Efbet (GR)')
BOOKS.add('Efbet (Net)')
BOOKS.add('EGB')
BOOKS.add('EGB SPORT')
BOOKS.add('EpicBet')
BOOKS.add('EsporteNetBet (BR)')
BOOKS.add('BetsBola')
BOOKS.add('EsporteNetSP (BR)')
BOOKS.add('EsporteNetVip (BR)')
BOOKS.add('EsportesDaSorte (BR)')
BOOKS.add('HiperBet (BR)')
BOOKS.add('EstorilSolCasinos (PT)')
BOOKS.add('EstrelaBet (BR)')
BOOKS.add('RabonaBet')
BOOKS.add('ToonieBet (CA)')
BOOKS.add('Etipos (SK)')
BOOKS.add('Etopaz (AZ)')
BOOKS.add('Etoto (PL)')
BOOKS.add('EuroBet (IT)')
BOOKS.add('EveryGame (EU)')
BOOKS.add('ExclusiveBet')
BOOKS.add('Betfinal')
BOOKS.add('IZIbet')
BOOKS.add('MrXBet')
BOOKS.add('ShangriLa')
BOOKS.add('UniClub (LT)')
BOOKS.add('F12Bet (BR)')
BOOKS.add('Fanatics')
BOOKS.add('FanDuel')
BOOKS.add('Betfair SB (BR)')
BOOKS.add('FanDuel (CT)')
BOOKS.add('Fastbet')
BOOKS.add('FavBet')
BOOKS.add('FavBet (UA)')
BOOKS.add('FB Sports')
BOOKS.add('Fonbet')
BOOKS.add('BeteryBet (IN)')
BOOKS.add('Bettery (RU)')
BOOKS.add('Fonbet (GR)')
BOOKS.add('Fonbet (KZ)')
BOOKS.add('Fonbet (Mobile)')
BOOKS.add('Pari (RU)')
BOOKS.add('Football (NG)')
BOOKS.add('Fortuna (PL)')
BOOKS.add('Fortuna (SK)')
BOOKS.add('Fortuna (CZ)')
BOOKS.add('FulltBet (BR)')
BOOKS.add('GalaxyBet')
BOOKS.add('SolisBet')
BOOKS.add('GaleraBet (BR)')
BOOKS.add('Gamdom')
BOOKS.add('Germania (HR)')
BOOKS.add('GGBet')
BOOKS.add('Freeggbet')
BOOKS.add('Vulkan')
BOOKS.add('Goalbet')
BOOKS.add('GoldBet (IT)')
BOOKS.add('BetFlag (IT)')
BOOKS.add('GoldBetShop (IT)')
BOOKS.add('IntralotShop (IT)')
BOOKS.add('Lottomatica (IT)')
BOOKS.add('GoldenPark (ES)')
BOOKS.add('CasinoBarcelona (ES)')
BOOKS.add('Solcasino (ES)')
BOOKS.add('GoldenPark (PT)')
BOOKS.add('GoldenVegas (BE)')
BOOKS.add('HKJC')
BOOKS.add('HoliganBet (TR)')
BOOKS.add('JojoBet')
BOOKS.add('Holland Casino (NL)')
BOOKS.add('Hollywoodbets')
BOOKS.add('Hollywoodbets (MZ)')
BOOKS.add('iForBet (PL)')
BOOKS.add('Ilotbet')
BOOKS.add('Interwetten')
BOOKS.add('Interwetten (ES)')
BOOKS.add('Interwetten (GR)')
BOOKS.add('IviBet')
BOOKS.add('20Bet')
BOOKS.add('Jacks (NL)')
BOOKS.add('Expekt')
BOOKS.add('JetCasino')
BOOKS.add('FreshCasino')
BOOKS.add('Rox (Sport)')
BOOKS.add('JSB')
BOOKS.add('Boltbet (GH)')
BOOKS.add('Primabet (GM)')
BOOKS.add('JugaBet (CL)')
BOOKS.add('Parimatch (TJ)')
BOOKS.add('KirolBet (ES)')
BOOKS.add('Apuestasvalor (ES)')
BOOKS.add('Aupabet (ES)')
BOOKS.add('Juegging (ES)')
BOOKS.add('KonfamBet')
BOOKS.add('LiveCasino365')
BOOKS.add('Kwiff')
BOOKS.add('Betkwiff')
BOOKS.add('Ladbrokes')
BOOKS.add('LeaderBet')
BOOKS.add('Lebull (PT)')
BOOKS.add('Leon')
BOOKS.add('Leon (RU)')
BOOKS.add('Twin')
BOOKS.add('LeoVegas')
BOOKS.add('Betmgm (BR)')
BOOKS.add('LeoVegas (SE)')
BOOKS.add('Williamhill (SE)')
BOOKS.add('LeoVegas (ES)')
BOOKS.add('LigaStavok (RU)')
BOOKS.add('LivescoreBet (NG)')
BOOKS.add('SunBet (ZA)')
BOOKS.add('LivescoreBet (UK)')
BOOKS.add('LivescoreBet (IE)')
BOOKS.add('LowVig (AG)')
BOOKS.add('LsBet')
BOOKS.add('ReloadBet')
BOOKS.add('TornadoBet')
BOOKS.add('Luckia (ES)')
BOOKS.add('Luckia (CO)')
BOOKS.add('Luckia (MX)')
BOOKS.add('LvBet')
BOOKS.add('LvBet (LV)')
BOOKS.add('LvBet (PL)')
BOOKS.add('Mansion (M88-BTI)')
BOOKS.add('Marathon')
BOOKS.add('Marathon (BY)')
BOOKS.add('Marathon (RU)')
BOOKS.add('MBet')
BOOKS.add('MarathonBet (DK)')
BOOKS.add('MarathonBet (ES)')
BOOKS.add('MarathonBet (IT)')
BOOKS.add('MarjoSports (BR)')
BOOKS.add('Matchbook-2%')
BOOKS.add('Maxbet (RS)')
BOOKS.add('Maxbet (BA)')
BOOKS.add('MaxLine (BY)')
BOOKS.add('Mcbookie')
BOOKS.add('StarSports')
BOOKS.add('Mcgames (BR)')
BOOKS.add('MelBet')
BOOKS.add('Betwinner')
BOOKS.add('DBbet')
BOOKS.add('MelBet (BI)')
BOOKS.add('MelBet (KE)')
BOOKS.add('MelBet (MN)')
BOOKS.add('Meridian')
BOOKS.add('Meridian (CY)')
BOOKS.add('Meridian (BE)')
BOOKS.add('Meridian')
BOOKS.add('Meridian (BA)')
BOOKS.add('Meridian (RS)')
BOOKS.add('Meridian (PE)')
BOOKS.add('JogaBets (MZ)')
BOOKS.add('Meridian (BR)')
BOOKS.add('Miseojeu+')
BOOKS.add('Misli (AZ)')
BOOKS.add('MostBet')
BOOKS.add('Mozzart')
BOOKS.add('Mozzart (BA)')
BOOKS.add('Mozzart (NG)')
BOOKS.add('Mozzart (RO)')
BOOKS.add('MrJack (BR)')
BOOKS.add('MSport (GH)')
BOOKS.add('MSport (NG)')
BOOKS.add('Mundoapostas')
BOOKS.add('Mystake')
BOOKS.add('31Bet')
BOOKS.add('9dBet (BR)')
BOOKS.add('Aposta1 (BR)')
BOOKS.add('Betfast')
BOOKS.add('Betfast (BR)')
BOOKS.add('Donbet')
BOOKS.add('Faz1Bet (BR)')
BOOKS.add('Freshbet')
BOOKS.add('Goldenbet')
BOOKS.add('Jackbit')
BOOKS.add('Mystake (Bet)')
BOOKS.add('Rolletto')
BOOKS.add('TivoBet (BR)')
BOOKS.add('Wjcasino (BR)')
BOOKS.add('N1Bet')
BOOKS.add('12Play')
BOOKS.add('Coins Game')
BOOKS.add('Wild')
BOOKS.add('YBets')
BOOKS.add('NaijaBet')
BOOKS.add('NairaBet')
BOOKS.add('Napoleon (BE)')
BOOKS.add('Neobet')
BOOKS.add('Neobet (CA)')
BOOKS.add('Neobet (DE)')
BOOKS.add('Nesine (TR)')
BOOKS.add('Bilyoner')
BOOKS.add('Misli (Com)')
BOOKS.add('Oley')
BOOKS.add('NetBet')
BOOKS.add('Bet777 (BE)')
BOOKS.add('Bet777 (ES)')
BOOKS.add('NetBet (GR)')
BOOKS.add('NetBet (BR)')
BOOKS.add('NetBet (IT)')
BOOKS.add('DaznBet (IT)')
BOOKS.add('OriginalBet (IT)')
BOOKS.add('Plexbet (IT)')
BOOKS.add('NetBet (RO)')
BOOKS.add('Nike (SK)')
BOOKS.add('NitroBetting (EU)')
BOOKS.add('Novibet (BR)')
BOOKS.add('Novibet (GR)')
BOOKS.add('Novibet (IE)')
BOOKS.add('Olimp')
BOOKS.add('Olimp (Bet)')
BOOKS.add('Olimpbet (KZ)')
BOOKS.add('Olimpkz')
BOOKS.add('OlimpoBet (PE)')
BOOKS.add('OlyBet (ES)')
BOOKS.add('OlyBet (EU)')
BOOKS.add('OlyBet (LT)')
BOOKS.add('Onabet (BR)')
BOOKS.add('Esporte365 (BR)')
BOOKS.add('LuckBet (BR)')
BOOKS.add('Luvabet (BR)')
BOOKS.add('Optibet (LT)')
BOOKS.add('Optibet (LV)')
BOOKS.add('Optibet (EE)')
BOOKS.add('OrbitX')
BOOKS.add('OrbiteX')
BOOKS.add('Paddy Power')
BOOKS.add('PameStoixima (GR)')
BOOKS.add('Parasino')
BOOKS.add('ApxBet')
BOOKS.add('Betonngliga')
BOOKS.add('LiderBet (BR)')
BOOKS.add('RealsBet (BR)')
BOOKS.add('Parimatch (KZ)')
BOOKS.add('BuddyBet (UA)')
BOOKS.add('Gra (Live)')
BOOKS.add('Paston (ES)')
BOOKS.add('SorteOnline (BR)')
BOOKS.add('Pin-up')
BOOKS.add('BetPlays')
BOOKS.add('Pin-up (RU)')
BOOKS.add('BaseBet')
BOOKS.add('Casino Spinamba')
BOOKS.add('Lucky Bird Casino')
BOOKS.add('MarsBet')
BOOKS.add('Pin-up (EN)')
BOOKS.add('Slottica')
BOOKS.add('Slotty Way')
BOOKS.add('Pinnacle ① ≥ 1.01')
BOOKS.add('P4578 (Asian) ① ≥ 1.01')
BOOKS.add('P4578 (EU) ① ≥ 1.01')
BOOKS.add('Pin135 (EU) ① ≥ 1.01')
BOOKS.add('Pinnacle (Bet) ① ≥ 1.01')
BOOKS.add('Pinnacle (BR) ① ≥ 1.01')
BOOKS.add('Pinnacle (SE) ① ≥ 1.01')
BOOKS.add('Pinnacle888 (Asian) ① ≥ 1.01')
BOOKS.add('Pinnacle888 (EU) ① ≥ 1.01')
BOOKS.add('Piwi247 (SB) ① ≥ 1.01')
BOOKS.add('PS3838 (Broker) ① ≥ 1.01')
BOOKS.add('Start975 (Asian) ① ≥ 1.01')
BOOKS.add('Start975 (EU) ① ≥ 1.01')
BOOKS.add('Piwi247')
BOOKS.add('PixBet (BR)')
BOOKS.add('Pixbet285')
BOOKS.add('Placard (PT)')
BOOKS.add('PlanetWin365 (IT)')
BOOKS.add('Playbonds')
BOOKS.add('PlayNow')
BOOKS.add('PMU (FR)')
BOOKS.add('PointsBet (AU)')
BOOKS.add('PokerStars')
BOOKS.add('PokerStars (DK)')
BOOKS.add('PokerStars (RO)')
BOOKS.add('PokerStars (FR)')
BOOKS.add('PokerStars (UK)')
BOOKS.add('PokerStars (CA)')
BOOKS.add('PokerStars (ES)')
BOOKS.add('PokerStars (IT)')
BOOKS.add('PokerStars (SE)')
BOOKS.add('PremierBet (MW)')
BOOKS.add('MercuryBet')
BOOKS.add('PremierBet (AO)')
BOOKS.add('PremierBet (CD)')
BOOKS.add('PremierBet (CG)')
BOOKS.add('PremierBet (CM)')
BOOKS.add('PremierBet (MZ)')
BOOKS.add('PremierBet (SN)')
BOOKS.add('PremierBet (TD)')
BOOKS.add('PremierBet (TZ)')
BOOKS.add('QQ101 (BTI)')
BOOKS.add('10Bet (KR)')
BOOKS.add('12Bet (BTI-ID)')
BOOKS.add('Fun88 (IN)')
BOOKS.add('QQ101 (IM Sports)')
BOOKS.add('RayBet')
BOOKS.add('RetaBet (ES)')
BOOKS.add('RetaBet (ES)')
BOOKS.add('RetaBet (PE)')
BOOKS.add('Rivalo (BR)')
BOOKS.add('Rivalo (CO)')
BOOKS.add('RuBet')
BOOKS.add('Rushbet (CO)')
BOOKS.add('GoldenBull (SE)')
BOOKS.add('Rushbet (MX)')
BOOKS.add('Sazka (CZ)')
BOOKS.add('Sbobet')
BOOKS.add('Pic5678')
BOOKS.add('SbobetAsia')
BOOKS.add('SboTop')
BOOKS.add('Sbobet (Esport)')
BOOKS.add('12Bet (Esport)')
BOOKS.add('BTC365 (Esport)')
BOOKS.add('VKGame')
BOOKS.add('SeuBet (BR)')
BOOKS.add('747 Live')
BOOKS.add('Sisal (IT)')
BOOKS.add('SkyBet')
BOOKS.add('SlotV (RO)')
BOOKS.add('KingsBet (CZ)')
BOOKS.add('Lottoland (AT)')
BOOKS.add('Smarkets')
BOOKS.add('Snai (IT)')
BOOKS.add('SolBet (PE)')
BOOKS.add('Solverde (PT)')
BOOKS.add('SorteNaBet (BR)')
BOOKS.add('Bateu (BR)')
BOOKS.add('Betfusion (BR)')
BOOKS.add('BullsBet (BR)')
BOOKS.add('SportBet (IT)')
BOOKS.add('BetX (IT)')
BOOKS.add('StarGame (IT)')
BOOKS.add('SportingWin')
BOOKS.add('Sportium (CO)')
BOOKS.add('Sportium (ES)')
BOOKS.add('Sportmarket')
BOOKS.add('SportsBet')
BOOKS.add('HugeWin')
BOOKS.add('SportsBet (AU)')
BOOKS.add('SportyBet')
BOOKS.add('SportyBet (BR)')
BOOKS.add('Stake')
BOOKS.add('Stake (BR)')
BOOKS.add('KTO (BR)')
BOOKS.add('Stake (CO)')
BOOKS.add('StanleyBet (BE) new')
BOOKS.add('StanleyBet (IT)')
BOOKS.add('StanleyBet (RO)')
BOOKS.add('Admiral (RO)')
BOOKS.add('Stoiximan (GR)')
BOOKS.add('Stoiximan (CY)')
BOOKS.add('Stoiximan (GR)')
BOOKS.add('STS (PL)')
BOOKS.add('SuperBet (BR)')
BOOKS.add('SuperBet (PL)')
BOOKS.add('SuperBet (RO)')
BOOKS.add('Surebet247')
BOOKS.add('SX Bet')
BOOKS.add('SynotTip (LV)')
BOOKS.add('SynotTip (CZ)')
BOOKS.add('SynotTip (SK)')
BOOKS.add('Tab (AU)')
BOOKS.add('TeApuesto (PE)')
BOOKS.add('TempoBet')
BOOKS.add('Tennisi')
BOOKS.add('Tennisi (Bet)')
BOOKS.add('Tennisi (KZ)')
BOOKS.add('Tipico')
BOOKS.add('Tipico (DE)')
BOOKS.add('TippmixPro (HU)')
BOOKS.add('Tipsport (CZ)')
BOOKS.add('Chance (CZ)')
BOOKS.add('Tipsport (SK)')
BOOKS.add('Tipwin (DE)')
BOOKS.add('Tipwin')
BOOKS.add('Tipwin (DK)')
BOOKS.add('Tipwin (SE)')
BOOKS.add('TonyBet')
BOOKS.add('TonyBet (NL)')
BOOKS.add('Vave')
BOOKS.add('TonyBet (ES)')
BOOKS.add('Topsport (LT)')
BOOKS.add('Toto (NL)')
BOOKS.add('TotoGaming (AM)')
BOOKS.add('1Win (Provider)')
BOOKS.add('Cannonbet')
BOOKS.add('CaptainsBet')
BOOKS.add('CaptainsBet (KE)')
BOOKS.add('Fortune Clock')
BOOKS.add('MelBet (NG)')
BOOKS.add('MelBet (RU)')
BOOKS.add('Sol.Casino')
BOOKS.add('Tinbet (PE)')
BOOKS.add('Winspirit')
BOOKS.add('Ubet (CY)')
BOOKS.add('Ubet (KZ)')
BOOKS.add('Betera (BY)')
BOOKS.add('Unibet')
BOOKS.add('32Red')
BOOKS.add('ATG (SE)')
BOOKS.add('Betmgm (NL)')
BOOKS.add('Betmgm (SE)')
BOOKS.add('Betmgm (UK)')
BOOKS.add('Casumo')
BOOKS.add('Casumo (ES)')
BOOKS.add('GrosvenorCasinos')
BOOKS.add('No Account Bet (SE)')
BOOKS.add('Paf')
BOOKS.add('Paf (ES)')
BOOKS.add('Paf (SE)')
BOOKS.add('PafBet (LV)')
BOOKS.add('Scoore (BE)')
BOOKS.add('Unibet (AU)')
BOOKS.add('Unibet (IT)')
BOOKS.add('Unibet (NL)')
BOOKS.add('Unibet (RO)')
BOOKS.add('Unibet (UK)')
BOOKS.add('Unibet (FR)')
BOOKS.add('VBet')
BOOKS.add('Bets60')
BOOKS.add('H2bet (BR)')
BOOKS.add('Hash636')
BOOKS.add('Uabet')
BOOKS.add('VBet (AM)')
BOOKS.add('VBet (BR)')
BOOKS.add('7Games (BR)')
BOOKS.add('Seguro (BR)')
BOOKS.add('VBet (LAT)')
BOOKS.add('VBet (NL)')
BOOKS.add('VBet (UK)')
BOOKS.add('Veikkaus (FI)')
BOOKS.add('Versus (ES)')
BOOKS.add('VirginBet')
BOOKS.add('Vulkan Bet')
BOOKS.add('W88Es')
BOOKS.add('William Hill')
BOOKS.add('Williamhill (ES)')
BOOKS.add('Williamhill (IT)')
BOOKS.add('Winamax (ES)')
BOOKS.add('Winamax (DE)')
BOOKS.add('Winamax (FR)')
BOOKS.add('WinBet (BG)')
BOOKS.add('WinBet (RO)')
BOOKS.add('Winline (RU)')
BOOKS.add('Winmasters')
BOOKS.add('Winmasters (CY)')
BOOKS.add('Winmasters (GR)')
BOOKS.add('Winmasters (RO)')
BOOKS.add('WonderBet (CO)')
BOOKS.add('WWin')
BOOKS.add('YaassCasino (ES)')
BOOKS.add('Yabo888')
BOOKS.add('Yajuego (CO)')
BOOKS.add('YSB')
BOOKS.add('Zamba (CO) new')
BOOKS.add('ZeBet')
BOOKS.add('ZeBet (BE)')
BOOKS.add('ZeBet (ES)')
BOOKS.add('ZeBet (FR)')
BOOKS.add('ParionsSport (FR)')
BOOKS.add('ZeBet (NL)')
BOOKS.add('Zenit')
BOOKS.add('Zenit (Win)')

TEXT_LANDING_PAGE = """

### **#ChasingSteamers Personal. Your personalized dropping odds feed.**

🔥 Robust, highly efficient betting strategy delivering unmatched profits.

🔥 Instant Market Alerts: Get notified the moment there's a significant price drop. Never miss an opportunity again!

🔥 One-Click Betting: With integrated deep links, go from notification to bet placement in a single click. Fast and furious!

🔥 Total Customization: Tailor your alerts by setting your minimum value threshold, preferred bookmakers, lookahead time, and more.

🔥 Multisport Support: With more than 40 sports supported, we've got you covered!.

🔥 Extensive Market Coverage: Dive into moneyline, spread, and totals across over 900 bookmakers.

❓**Not sure how you can take advantage?**

👉 Then I recommend heading over to my website for a detailed description https://bettingiscool.com/pinnacle-steamers/

"""

