TABLE_LOG = 'log'

USER_DOMAIN_CHANGES = dict()
USER_DOMAIN_CHANGES.update({'contact@bettingiscool.com': {'interwetten.de': 'interwetten.com', 'tipico.de': 'tipico.at'}})

BOOKS = dict()
BOOKS.update({'10bet': '10bet'})
BOOKS.update({'188bet': '188BET'})
BOOKS.update({'18bet': '18Bet'})
BOOKS.update({'198bet': '198Bet'})
BOOKS.update({'1bet': '1Bet'})
BOOKS.update({'1xbet': '1xBet'})
BOOKS.update({'1xbit': '1xBit'})
BOOKS.update({'20bet': '20Bet'})
BOOKS.update({'22bet': '22Bet'})
BOOKS.update({'31bet': '31Bet'})
BOOKS.update({'32red': '32Red'})
BOOKS.update({'3et': '3et'})
BOOKS.update({'7bet.lt': '7Bet LT'})
BOOKS.update({'admiral': 'Admiral AT'})
BOOKS.update({'admiralbet.ro': 'AdmiralBet RO'})
BOOKS.update({'allbritishcasino': 'All British Casino'})
BOOKS.update({'alphawin': 'AlphaWin'})
BOOKS.update({'apuestatotal': 'Apuesta Total'})
BOOKS.update({'atg.se': 'ATG SE'})
BOOKS.update({'ballybet': 'Bally Bet'})
BOOKS.update({'bcgame': 'BC.Game'})
BOOKS.update({'bet3000': 'Bet3000'})
BOOKS.update({'bet365': 'bet365'})
BOOKS.update({'bet365-test': 'bet365'})
BOOKS.update({'bet365.de': 'bet365 DE'})
BOOKS.update({'bet9ja': 'Bet9ja'})
BOOKS.update({'betano': 'Betano'})
BOOKS.update({'betathome': 'Bet-At-Home'})
BOOKS.update({'betcenter.be': 'Betcenter BE'})
BOOKS.update({'betcity': 'Betcity NL'})
BOOKS.update({'betclic.fr': 'BetClic FR'})
BOOKS.update({'betclic.pl': 'BetClic PL'})
BOOKS.update({'betclic.pt': 'BetClic PT'})
BOOKS.update({'betfair-ex': 'BetFair Exchange'})
BOOKS.update({'betfair-spb': 'BetFair Sportsbook'})
BOOKS.update({'betfred': 'Betfred'})
BOOKS.update({'betfury': 'Betfury'})
BOOKS.update({'betibet': 'BetiBet'})
BOOKS.update({'betika': 'Betika KE'})
BOOKS.update({'betisn': 'BetISN'})
BOOKS.update({'betmgm': 'BetMGM'})
BOOKS.update({'betnacional': 'Betnacional'})
BOOKS.update({'betonred': 'BetOnRed'})
BOOKS.update({'betparx': 'BetParx'})
BOOKS.update({'betplay': 'BetPlay'})
BOOKS.update({'betrivers': 'BetRivers'})
BOOKS.update({'betsafe': 'Betsafe'})
BOOKS.update({'betsafe.lt': 'Betsafe LT'})
BOOKS.update({'betsson': 'Betsson'})
BOOKS.update({'betuk': 'BetUK'})
BOOKS.update({'betvictor': 'BetVictor'})
BOOKS.update({'betway': 'Betway'})
BOOKS.update({'betwinner': 'BetWinner'})
BOOKS.update({'bfb247': 'BFB247'})
BOOKS.update({'bingoal.be': 'Bingoal BE'})
BOOKS.update({'bluechip': 'Bluechip'})
BOOKS.update({'bolsadeaposta-spb': 'Bolsa de Aposta Sportsbook'})
BOOKS.update({'bookmaker.eu': 'BookMaker EU'})
BOOKS.update({'borgata': 'Borgata Online Sports'})
BOOKS.update({'boylesports': 'BoyleSports'})
BOOKS.update({'bpremium': 'Bpremium'})
BOOKS.update({'bwin': 'Bwin'})
BOOKS.update({'bwin.es': 'Bwin ES'})
BOOKS.update({'bwin.fr': 'Bwin FR'})
BOOKS.update({'bwin.it': 'Bwin IT'})
BOOKS.update({'caliente': 'Caliente MX'})
BOOKS.update({'campeonbet': 'CampeonBet'})
BOOKS.update({'cashpoint': 'CASHPOINT'})
BOOKS.update({'cloudbet': 'Cloudbet'})
BOOKS.update({'coolbet': 'Coolbet'})
BOOKS.update({'coral': 'Coral'})
BOOKS.update({'crazybuzzer': 'CrazyBuzzer'})
BOOKS.update({'cricbaba': 'Cricbaba'})
BOOKS.update({'dachbet': 'DACHBET'})
BOOKS.update({'dafabet': 'Dafabet'})
BOOKS.update({'draftkings': 'Draftkings'})
BOOKS.update({'dreambet': 'Dream.bet'})
BOOKS.update({'duelbits': 'Duelbits'})
BOOKS.update({'espnbet': 'ESPN Bet'})
BOOKS.update({'esportivabet': 'Esportiva Bet'})
BOOKS.update({'estrelabet': 'Estrela Bet'})
BOOKS.update({'fanduel': 'FanDuel'})
BOOKS.update({'fdj': 'FDJ'})
BOOKS.update({'fezbet': 'FEZbet'})
BOOKS.update({'fortebet.ug': 'Fortebet UG'})
BOOKS.update({'freshbet': 'FreshBet'})
BOOKS.update({'fun88.co.uk': 'Fun88 UK'})
BOOKS.update({'gamebookers': 'Gamebookers'})
BOOKS.update({'genybet.fr': 'Genybet FR'})
BOOKS.update({'goldenbet': 'Goldenbet'})
BOOKS.update({'greatwin': 'GreatWin'})
BOOKS.update({'grosvenor': 'Grosvenor'})
BOOKS.update({'hollywoodbets': 'Hollywoodbets'})
BOOKS.update({'indibet': 'INDIBET'})
BOOKS.update({'inkabet': 'Inkabet'})
BOOKS.update({'interwetten': 'Interwetten'})
BOOKS.update({'ivibet': 'IviBet'})
BOOKS.update({'jackbit': 'JackBit'})
BOOKS.update({'jacks': 'Jacks'})
BOOKS.update({'kaiyun': 'Kaiyun Sports'})
BOOKS.update({'kto': 'KTO'})
BOOKS.update({'ladbrokes': 'Ladbrokes'})
BOOKS.update({'ladbrokes.de': 'Ladbrokes DE'})
BOOKS.update({'leovegas': 'LeoVegas'})
BOOKS.update({'librabet': 'LibraBet'})
BOOKS.update({'lilibet': 'LiliBet'})
BOOKS.update({'livescorebet': 'LiveScoreBet'})
BOOKS.update({'lottoland': 'Lottoland'})
BOOKS.update({'marcaapuestas': 'MARCAapuestas'})
BOOKS.update({'megapari': 'MegaPari'})
BOOKS.update({'melbet': 'MelBet'})
BOOKS.update({'merkurbets': 'Merkur Bets'})
BOOKS.update({'mozzartbet': 'Mozzart Bet'})
BOOKS.update({'mrbit.ro': 'MrBit RO'})
BOOKS.update({'mrgreen': 'MrGreen'})
BOOKS.update({'mrjack.bet': 'Mr. Jack'})
BOOKS.update({'mystake': 'MyStake'})
BOOKS.update({'n1bet': 'N1Bet'})
BOOKS.update({'napoleonsports.be': 'Napoleon Sports BE'})
BOOKS.update({'netbet': 'NetBet'})
BOOKS.update({'netbet.fr': 'NetBet FR'})
BOOKS.update({'nextbet': 'Nextbet'})
BOOKS.update({'ninecasino': 'Ninecasino'})
BOOKS.update({'nordicbet': 'NordicBet'})
BOOKS.update({'oddset': 'OddSet'})
BOOKS.update({'odibets': 'OdiBets'})
BOOKS.update({'paddypower': 'Paddy Power'})
BOOKS.update({'paf': 'PAF'})
BOOKS.update({'pagbet': 'PAGBET'})
BOOKS.update({'parimatch.co.uk': 'PariMatch UK'})
BOOKS.update({'pb77': 'PremiumBet77'})
BOOKS.update({'pinnacle': 'Pinnacle Sports'})
BOOKS.update({'piwi247': 'Piwi247'})
BOOKS.update({'pixbet': 'Pix Bet'})
BOOKS.update({'pmu': 'PMU'})
BOOKS.update({'pointsbet': 'PointsBet'})
BOOKS.update({'pokerstars': 'PokerStars'})
BOOKS.update({'pokerstars.es': 'PokerStars ES'})
BOOKS.update({'pokerstars.fr': 'PokerStars FR'})
BOOKS.update({'pokerstars.it': 'PokerStars IT'})
BOOKS.update({'pokerstars.ro': 'PokerStars RO'})
BOOKS.update({'pokerstars.uk': 'PokerStars UK'})
BOOKS.update({'powbet': 'Powbet'})
BOOKS.update({'ps3838': 'PS3838'})
BOOKS.update({'qbet': 'Qbet'})
BOOKS.update({'quickwin': 'QuickWin'})
BOOKS.update({'rabona': 'Rabona'})
BOOKS.update({'rajbets': 'RajBet'})
BOOKS.update({'rocketplay': 'RocketPlay'})
BOOKS.update({'rollbit': 'Rollbit'})
BOOKS.update({'rolletto': 'Rolletto'})
BOOKS.update({'roobet': 'Roobet'})
BOOKS.update({'rushbet.co': 'Rushbet CO'})
BOOKS.update({'sbobet': 'SBOBET'})
BOOKS.update({'sharpbet': 'SharpBet'})
BOOKS.update({'singbet': 'SingBet'})
BOOKS.update({'sisal': 'Sisal IT'})
BOOKS.update({'skybet': 'SkyBet'})
BOOKS.update({'sport888': '888Sport'})
BOOKS.update({'sport888.it': '888Sport IT'})
BOOKS.update({'sportaza': 'Sportaza'})
BOOKS.update({'sportingbet': 'SportingBet'})
BOOKS.update({'sportingindex': 'Sporting Index'})
BOOKS.update({'sporttip': 'Sporttip'})
BOOKS.update({'sportwetten.de': 'sportwetten.de'})
BOOKS.update({'sportybet': 'SportyBet'})
BOOKS.update({'spreadex': 'Spreadex'})
BOOKS.update({'stake': 'Stake.com'})
BOOKS.update({'starcasino': 'Starcasino BE'})
BOOKS.update({'stoiximan': 'Stoiximan'})
BOOKS.update({'sts.pl': 'STS PL'})
BOOKS.update({'sugarhouse': 'SugarHouse'})
BOOKS.update({'sultanbet': 'Sultanbet'})
BOOKS.update({'superbet': 'Superbet'})
BOOKS.update({'svenskaspel': 'Svenska Spel'})
BOOKS.update({'tab.com.au': 'Tab AU'})
BOOKS.update({'tabtouch': 'TABtouch'})
BOOKS.update({'thescore': 'theScore'})
BOOKS.update({'tipico': 'Tipico DE'})
BOOKS.update({'tippmixpro': 'TippmixPRO'})
BOOKS.update({'tiptorro': 'TipTorro'})
BOOKS.update({'tipwin': 'tipwin'})
BOOKS.update({'unibet': 'Unibet'})
BOOKS.update({'unibet.be': 'Unibet BE'})
BOOKS.update({'unibet.co.uk': 'Unibet UK'})
BOOKS.update({'unibet.com.au': 'Unibet AU'})
BOOKS.update({'unibet.dk': 'Unibet DK'})
BOOKS.update({'unibet.es': 'Unibet ES'})
BOOKS.update({'unibet.fr': 'Unibet FR'})
BOOKS.update({'unibet.it': 'Unibet IT'})
BOOKS.update({'unibet.nl': 'Unibet NL'})
BOOKS.update({'unibet.ro': 'Unibet RO'})
BOOKS.update({'unibet.se': 'Unibet SE'})
BOOKS.update({'vave': 'Vave'})
BOOKS.update({'vbet': 'Vbet'})
BOOKS.update({'vertex': 'Vertex'})
BOOKS.update({'virginbet': 'Virginbet'})
BOOKS.update({'vistabet': 'Vistabet'})
BOOKS.update({'wazamba': 'Wazamba'})
BOOKS.update({'weltbet': 'WELTBET'})
BOOKS.update({'wettarena': 'Wettarena'})
BOOKS.update({'williamhill': 'WilliamHill'})
BOOKS.update({'winamax.de': 'Winamax DE'})
BOOKS.update({'winamax.es': 'Winamax ES'})
BOOKS.update({'winamax.fr': 'Winamax FR'})
BOOKS.update({'winbet': 'WinBet BG'})
BOOKS.update({'winbet.ro': 'WinBet RO'})
BOOKS.update({'winpot.mx': 'Winpot MX'})
BOOKS.update({'winz.io': 'Winz.io'})
BOOKS.update({'wolfbet': 'WOLFBET'})
BOOKS.update({'wplay.co': 'WPlay CO'})
BOOKS.update({'yesplay': 'YesPlay'})
BOOKS.update({'zebet.fr': 'ZEbet FR'})
